### ISSUE TITLE
Database error with v1.0.3

### ISSUE THREAD

**Issue by FatherWh0** [novucs/factions-top#1]
I am attempting a fresh load with v1.0.3.
http://paste.md-5.net/vudebayofa.avrasm
The factionstop folder only has the config.yml, no database folder.
Paper #820
Massivecraft Factions 2.8.19
Massivecraft Vampire 2.8.19

**Comment by novucs** [comment]
Do you not have H2 automatically downloaded in your ./lib/ folder?

**Comment by FatherWh0** [comment]
http://prnt.sc/by0ru3
Verified both on my test server and live server.

**Comment by novucs** [comment]
I am unable to reproduce your error with this exact setup:
- Paper #820
- Massivecraft Factions 2.8.19
- Massivecraft Vampire 2.8.19
- Massivecraft Core 2.8.19
- FactionsTop 1.0.3

Could you possibly try to find if there are any plugins creating a conflict somehow?

**Comment by novucs** [comment]
Issue has been resolved.
