### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by TheIronMinerLv** [novucs/factions-top#10]
Hello, so there is a error, when my server starts, and because of that the Factions Top doesn't work at all. Idk why there is that error, because few hours ago (before I restarted server - I didn't made any changes) it worked as it was intended.

So here is the error: http://pastebin.com/bmZivBq6
My plugins list: http://prntscr.com/cu70na
I'm using newest version of your plugin and newest Paperspigot 1.8.8.

Please help!

**Comment by novucs** [comment]
What version of Factions was this running? Apologies for the super late response.

**Comment by novucs** [comment]
Unable to reproduce on the latest version. Assuming this was to do with the MassiveCore update, closing issue.
