### ISSUE TITLE
Upcoming FactionsUUID breakage

### ISSUE THREAD

**Issue by CmdrKittens** [novucs/factions-top#115]
The next release of FactionsUUID, coming *soonish*, will break the integration due to a refactor removing some legacy packages.

`com.massivecraft.factions.zcore.persist.MemoryBoard` is now `com.massivecraft.factions.data.MemoryBoard`

Same with the other class in that zcore package. Since everything else is reflection based in that hook, it may be worth doing `Class.forName` calls, but could also just be updated since older version of the FactionsUUID plugin will not be supported. 

At present, the change can be compiled against with maven version  `1.6.9.5-U0.4.9` but upon release of 0.5.0,  `1.6.9.5-U0.5.0` will reflect the change as well.

PR submitted over at #116 

For FactionsUUID users, this link will (until novucs gets the chance to update things) have a download for a fork of this plugin that only supports FactionsUUID on the latest version (0.5.0+) https://github.com/CmdrKittens/factions-top/releases

This way, people can use a working fork while we wait. Will clear it out once you get the chance to update here :)

**Comment by Phoenix616** [comment]
Fixed since cb4f35ea0c3aa9606ba5d97f6f6900f97da5ba7f
