### ISSUE TITLE
Failed to get h2 driver instance

### ISSUE THREAD

**Issue by DevelopmentHigh** [novucs/factions-top#123]
Version  1.8.8 paper spigot , factions massive core plugin with massive core. they say:

![pomoc1](https://user-images.githubusercontent.com/61356848/75095544-f6f59880-5595-11ea-8ebb-71e520b36bfb.png)

**Comment by Phoenix616** [comment]
This has nothing to do with Factions ;)

**Comment by DevelopmentHigh** [comment]
> This has nothing to do with Factions ;) Please test if the issue is solved after the reboot that was suggested by FactionsTop.

When i type in my chat they say nothing - sry for my bad english

i dont know how to fix that can you help me?

**Comment by Phoenix616** [comment]
Did you restart and the same error occurred? If so please post the new one again.

**Comment by DevelopmentHigh** [comment]
Yes i restart the server and delete all plugins and again this plugin doesn't work, when i type in chat  /plugins they are red and say me in console like in another text what i was send

**Comment by DevelopmentHigh** [comment]
Hey i know what is wrong,  i dont have  database, and i dont have access to my database how now  i can connect this plugin? help me please

**Comment by DevelopmentHigh** [comment]
> Did you restart and the same error occurred? If so please post the new one again.

can you help me?

**Comment by Phoenix616** [comment]
Can you check if the `h2-1.4.192.jar` exists in your `lib` folder in the server root?

**Comment by DevelopmentHigh** [comment]
> Can you check if the `h2-1.4.192.jar` exists in your `lib` folder in the server root?

 h2-1.4.192.jar yes i have

**Comment by Phoenix616** [comment]
Does it work with the fix from yesterday?

**Comment by DevelopmentHigh** [comment]
> Does it work with the fix from yesterday?

i must download new version? if it is send me link and i will reply you

**Comment by Phoenix616** [comment]
Delete the h2 file in the lib folder and then run the latest [development build](https://ci.minebench.de/job/FactionsTop/).

**Comment by DevelopmentHigh** [comment]
> Delete the h2 file in the lib folder and then run the latest [development build](https://ci.minebench.de/job/FactionsTop/).

i will try to do this now

**Comment by DevelopmentHigh** [comment]
> Delete the h2 file in the lib folder and then run the latest [development build](https://ci.minebench.de/job/FactionsTop/).

i dont have permission to delete lib/h2-1.4.192.jar

**Comment by DevelopmentHigh** [comment]
> Delete the h2 file in the lib folder and then run the latest [development build](https://ci.minebench.de/job/FactionsTop/).

i add the plugin again doesn't work

**Comment by DevelopmentHigh** [comment]
i cant fix this can you help me?

**Comment by Phoenix616** [comment]
Did you delete the old h2 file? Otherwise it wont work.

**Comment by DevelopmentHigh** [comment]
I am using winscp and they say me i doesn't have permission to delete

**Comment by DevelopmentHigh** [comment]
What i can use do delete this folder they all time say me i doesn't have permission and also when i stop server they disconnect winscp

**Comment by Phoenix616** [comment]
Then you are going to have to solve your file permission issue first. It's your server so you should have access to everything. (And if you are not the admin/person with full access, contact them)

**Comment by DevelopmentHigh** [comment]
i do that again, the plugin works, but wen i type  /ftop they say me nothing

**Comment by DevelopmentHigh** [comment]
Can i just remove Factions massivecore and install factionsuuid?

**Comment by Phoenix616** [comment]
Please open a separate issue if you gave other problems that are unrelated to this one.

**Comment by DevelopmentHigh** [comment]
> Please open a separate issue if you gave other problems that are unrelated to this one.

I delete the lib folder, and delete factions plugin and massivecore  and reinstall massivecore and factions and new factions top, now again does not work

**Comment by DevelopmentHigh** [comment]
> Please open a separate issue if you gave other problems that are unrelated to this one.

I fix that thank you :)
