### ISSUE TITLE
Could you help me?

### ISSUE THREAD

**Issue by sandor111** [novucs/factions-top#13]
What is this exactly? And is the project still alive could you help me with one of my project? leave a comment plz

**Comment by novucs** [comment]
1. This is a Bukkit plugin to calculate the most wealthy factions on a server
2. I no longer have much time at my disposal and will only be making paid edits
3. What is your project?

**Comment by sandor111** [comment]
Its not really my project its just that simple clans and precious stones don't work together anymore maybe you could fix it or make a faction add on which allows people to do / f war which will make the land of the defender raidable for the attacker

**Comment by sandor111** [comment]
I would really appreciatie that

**Comment by novucs** [comment]
Nope, sorry but I do not have the spare time to help you.
