### ISSUE TITLE
Faction Top Plugin isn't working on my server

### ISSUE THREAD

**Issue by Charpzy** [novucs/factions-top#138]
Spigot - 1.8.8
FactionsUUID - 1.6.9.5-u0.2.2-b116
FactionsTop 1.2.1-SNAPSHOT

Everytime i start the server i get the below error:
https://pastebin.com/mGhAKD99

Any ideas on how I can fix this?

**Comment by Phoenix616** [comment]
Aa stated on line 4 your factions version is incompatible. Please update it to a more modern version (latest is 1.6.9.5-U0.5.13-b230) or use an older FactionsTop version if for whatever reason you want to stick to such an outdated version.
