### ISSUE TITLE
Support For SaberFactions

### ISSUE THREAD

**Issue by FlyingJungler** [novucs/factions-top#139]
Hey i wanted to ask you guys if you will add support for saberfactions

**Comment by Phoenix616** [comment]
What issues do you have when running this plugin with SaberFactions?

**Comment by FlyingJungler** [comment]
Am using saberfactions as my factions plugin massive core 2.14 and when I start my server it gives this error 
[01:41:32 INFO]: [FactionsTop] Enabling FactionsTop v1.2.1-SNAPSHOT 

[01:41:33 ERROR]: [FactionsTop] Factions version found is incompatible!

**Comment by Phoenix616** [comment]
You seem to be running an old version of FactionsTop, please test with the latest [development build](https://ci.minebench.de/job/FactionsTop/) and ideally provide the full log if it still doesn't work with that.

**Comment by FlyingJungler** [comment]
I downloaded and installed the new dev build from the link and still got the same problem here is the paste bin
https://pastebin.com/XAqWGNYe

**Comment by Phoenix616** [comment]
Well that's not really the full log but could you also provide the exact version of SaberFactions just for reference? (As your log doesn't contain that)

**Comment by FlyingJungler** [comment]
Hey sorry for not providing the version of SaberFactions i am using SaberFactions Version 2.3.9-RC
and here is the paste bin https://pastebin.com/7wxZnxnZ

**Comment by Phoenix616** [comment]
It seems like the issue is caused by the recent update (cb4f35ea0c3aa9606ba5d97f6f6900f97da5ba7f) to make it compatible with the new Factions-UUID versions. It seems like SaberFactions hasn't updated to reflect the change in Factions-UUID yet so I guess we really have to add backwards compatibility for that :S

**Comment by CmdrKittens** [comment]
Welcome to my personal hell! :(
