### ISSUE TITLE
Super lag (when there is a lot of factions/data?)

### ISSUE THREAD

**Issue by CheatSupport** [novucs/factions-top#14]
https://gyazo.com/98efac64b0a44f996fb226d932f71c01

**Comment by novucs** [comment]
Are you automatically scheduling the use of "/ftoprecalc"?
Are chests enabled?

Please obtain the latest jar and send me a good tree view breakdown of the resource usage by FactionsTop, using YourKit. Without the extra information, I will not be unable to debug this abnormal resource usage for you.

**Comment by novucs** [comment]
Was an issue with the large number of chests, sadly I have not yet thought of a better way to safely implement their live statistics. Larger servers are simply better off disabling chest updates if they become a problem.
