### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by XipsAhoy** [novucs/factions-top#142]
This shows up when I start my server!

ERROR Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
20.09 04:46:16 [Server] INFO java.lang.NoClassDefFoundError: com/massivecraft/factions/zcore/persist/MemoryBoard
20.09 04:46:16 [Server] INFO at net.novucs.ftop.hook.Factions0106.initialize(Factions0106.java:42) ~[?:?]
20.09 04:46:16 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_265]
20.09 04:46:16 [Server] INFO at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:371) ~[?:?]
20.09 04:46:16 [Server] INFO at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:138) ~[?:?]
20.09 04:46:16 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper.jar:git-PaperSpigot-"8b18730"]
20.09 04:46:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
20.09 04:46:16 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.zcore.persist.MemoryBoard

I am using factions UUID

**Comment by Phoenix616** [comment]
- [ ] You are running an outdated version. This is already fixed. Us the latest [dev build](https://ci.minebench.de/view/Various/job/FactionsTop/).
