### ISSUE TITLE
Iron golems not working

### ISSUE THREAD

**Issue by SnakeDaoust1232** [novucs/factions-top#15]
https://gyazo.com/2bb4faab3bcb27fd65ba59d616e13550

**Comment by VipFTW** [comment]
Found the fix, so go all the way down until you see "spawner-prices:" under that put in "    iron_golem: 1200000.0". Scroll all the way up and put in for the chat message "    - '&dIronGolem: &b{count:spawner:iron_golem}'" You should be goo from here, just go to minecraft and do /ftoprecalc then your done.

**Comment by novucs** [comment]
Thanks @VipFTW
