### ISSUE TITLE
Update PlaceholderAPI hook to new PAPI-2.10.7+ method

### ISSUE THREAD

**Issue by TheJoshue** [novucs/factions-top#150]
Hello good people,
I wanted to ask, could the placeholderAPI hook be updated to the latest version? because now it supports only PAPI versions 2.10.6 and below
-So this is that "Expansion Update": https://www.spigotmc.org/resources/placeholderapi.6245/update?update=351340
-Useful to check out for people who code and who would potentially do update this: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion

I am very bad at programming, but if i could help i really would, so i can only support you for this if you want through paypal money

Thank you in advance.

**Comment by Phoenix616** [comment]
Should be fixed by 1a7314a59b4d95931544155308ada197dfe591c4 and bc062815d9b2b39c7ca7032eb7b000af04612d7b.
