### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by rejvic** [novucs/factions-top#151]
Is is compatible with Saber Factions? If not, will it ever be? Thanks in advance!

**Comment by Phoenix616** [comment]
Please search existing issues before opening one. According to [this comment](https://github.com/novucs/factions-top/issues/149#issuecomment-932835780) a certain version works. If you run into issues then please open an issue which includes all the used server and plugin versions.

**Comment by rejvic** [comment]
I already found this and used the 13th version from Jenkins, however the error still persists https://pastebin.com/gRfWXMq9. I already tried rebooting as well but to no avail. Any tips?
