### ISSUE TITLE
Database issue.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [novucs/factions-top#17]
This is spamming my console when I don't even have mysql enabled.

Error: https://gyazo.com/de8bebcbb453dc36160ad9940a8f99dd

Config: https://hastebin.com/garuvirero.bash

**Comment by novucs** [comment]
Unable to access the h2 database, it still utilizes a password so perhaps at one point you modified the default password and changed it back? There could even be permission issues to the database file `jdbc:h2:./plugins/FactionsTop/database`. If it were the former and you do not remember the password, I'd suggest simply resetting the database and allowing the plugin to re-synchronize normally.

**Comment by SnakeDaoust1232** [comment]
https://gyazo.com/f4044a2dceba3070cc97fcc215be6f8b

I can confirm that with using the default settings, its still spamming this error.

**Comment by SnakeDaoust1232** [comment]
https://gyazo.com/67d1e0ea64a40bdd6d4c52736fc7118e
