### ISSUE TITLE
Language Issue (NBSP)

### ISSUE THREAD

**Issue by Actrozz** [novucs/factions-top#18]
I don't know how to fix this

![bug](https://cloud.githubusercontent.com/assets/25966569/23235075/28a172ce-f922-11e6-92a7-1c8639303801.png)

**Comment by novucs** [comment]
Modify `currency-format` to use valid characters.

**Comment by M0dEx** [comment]
This does not work, because DecimalFormat class overrides your custom format with the current locale format. This issue is still present even today.
