### ISSUE TITLE
DataBase issue. Sometime throught the day it stops re-syncing.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [novucs/factions-top#19]
Error: https://gyazo.com/f4044a2dceba3070cc97fcc215be6f8b
Config: https://hastebin.com/uzohivuzeb.bash

I tried deleting the database and letting it regen a new database, but it wont even regen a new one. It just gives me that error ^

The only way i can get it to "temporarily" work is by restarting the server. Then it generates a database and im able to use the plugin for a bit before it stops working.

**Comment by KillerAntMC** [comment]
Error: https://gyazo.com/f9a6e26bb7c6d14c537a9a0e68831748
Config: http://pastebin.com/XByN2sg7

I've been getting this error as well.

**Comment by novucs** [comment]
The latest build has a workaround for this.
