### ISSUE TITLE
Won't Load

### ISSUE THREAD

**Issue by CheatSupport** [novucs/factions-top#2]
Error Log: http://pastebin.com/gU4pJswD

**Comment by Sudzzy** [comment]
Apologies, I am away on holiday right now so my responses are going to be very slow. Could you possibly specify all details about your server? Maybe try using a later version of paper/spigot for 1.8 could fix this. Or it may even be a plugin compatibility issue. Let me know if you find out what plugin is causing this or if switching server build fixed it.

Thanks!

**Comment by novucs** [comment]
Apologies, I am away on holiday right now so my responses are going to be very slow. Could you possibly specify all details about your server? Maybe try using a later version of paper/spigot for 1.8 could fix this. Or it may even be a plugin compatibility issue. Let me know if you find out what plugin is causing this or if switching server build fixed it.

Thanks!

**Comment by novucs** [comment]
Issue has been resolved.
