### ISSUE TITLE
SilkTouch Spawners Bug 

### ISSUE THREAD

**Issue by SnakeDaoust1232** [novucs/factions-top#20]
Using chest events, if you silk touch a spawner, and place it in a chest, it doesnt recognize the spawner. Spawners that are not silktouched are added normally and work fine.

Feature Request: A placeholder showing how long until the next ftop recalc.

**Comment by SnakeDaoust1232** [comment]
bump

**Comment by SnakeDaoust1232** [comment]
The new silkspawners fixes this. (CLOSED)

**Comment by novucs** [comment]
Thanks for the update.
