### ISSUE TITLE
FactionTop PlaceHolder

### ISSUE THREAD

**Issue by Actrozzz** [novucs/factions-top#22]
Hello,

I added the placeholder for the ranks and I have this problem.

When I don't have a faction, everything is fine :
![1](https://cloud.githubusercontent.com/assets/26993837/24785503/6c9d2aae-1b28-11e7-8e19-b49e1e187ec5.png)

When I create a faction but I don't claim any land, it shows [#0] instead of what I put in the config ( rank-not-found: '' )
![2](https://cloud.githubusercontent.com/assets/26993837/24785631/87ccab3c-1b29-11e7-9fd0-ed36ca54d2a5.png)

My friend is in the faction loll and it shows #1 which is what we want but we would like to at least be able to change the [#0] to whatever we want.

I use FactionUUID and FactionsTop version 1.1.2-SNAPSHOT

**Comment by novucs** [comment]
Thanks for the report, fixed.
Download here: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE
Commit here: https://github.com/novucs/factions-top/commit/ce1c78678f374e0e81ab932b5fcd313c7597eb90
