### ISSUE TITLE
Skipping BlockEntity with id 

### ISSUE THREAD

**Issue by DesignerHD** [novucs/factions-top#23]
Hello,

I have noticed that there is a problem with some spawners, I have followed what it says about going to the.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

The types that don't work is 

IRON_GOLEM
PIG_ZOMBIE
MUSHROOM_COW

I have found this out because I put them in a different chest to all the other spawners.

Any fix for this?

Thanks,

DesignerHD / T16

**Comment by novucs** [comment]
You need to give them a worth value.
