### ISSUE TITLE
Stacktrace and throwing internal error

### ISSUE THREAD

**Issue by SnakeDaoust1232** [novucs/factions-top#24]
When some of my players type the f top command it gives this error and they "only see top 1 and 2 factions"

Config: https://hastebin.com/dasadiwapa.bash

https://gyazo.com/f3c7727d108a92a6c0aa103573fc37bc

**Comment by novucs** [comment]
Are you running a custom build? I cannot see a way how a null value is inserted into the ordered faction worths with the latest version.

**Comment by SnakeDaoust1232** [comment]
I'm using the most recent build on the spigot page. I'm using TacoSpigot. Which is a fork of paperspigot. That might be the reason but idk.

**Comment by novucs** [comment]
Sadly I still see no way to reproduce this, could you please tell me the exact version of factions you were using?
