### ISSUE TITLE
F Top bug

### ISSUE THREAD

**Issue by Matthew777k** [novucs/factions-top#25]
When any block is blown up and replaced in land, it doesn't remove the block from the f top value and just keeps adding onto it. 
https://youtu.be/CR3QiSwpjDg

**Comment by novucs** [comment]
That would be a bug created by your spawner plugin, the EntityExplodeEvent is being cancelled. Please contact the author of that plugin and tell them to fire the EntityExplodeEvent with the blocks being destroyed in order to maintain functionality.
