### ISSUE TITLE
Player-Balances

### ISSUE THREAD

**Issue by SrBathTub** [novucs/factions-top#27]
This has been an issue for quite a while now but your player balance listeners haven't been working, therefore I have been unable to allow for player values to count in a factions overall value. Can you please fix this so that my factions server can release. This is actually the last thing I need and people have been begging for this for quite a while, I just thought this would be fixed by now, no offense.

**Comment by novucs** [comment]
Could you please specify exactly how player balances are "not working" for you with a reproducible test case?

**Comment by novucs** [comment]
No response. Player balances appear to be working completely fine and no other complaints of this sort have been made. I'll assume this is either a false bug report or you had a conflicting plugin.
