### ISSUE TITLE
Randomly didnt startup once

### ISSUE THREAD

**Issue by SnakeDaoust1232** [novucs/factions-top#28]
My players were complaining that Ftop wasn't working, so i checked the startup log and this was there. I restarted the server and the plugin booted up fine. wtf

Latest version of the plugin and using tacospigot 1.8.8

Log: https://hastebin.com/epewowuzey.vbs

**Comment by novucs** [comment]
Issue has been resolved in latest build: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE
