### ISSUE TITLE
Reload Problem

### ISSUE THREAD

**Issue by LittleGamerPlayz** [novucs/factions-top#32]
Whenever I reload my server the /F Top list resets and instead of saying the factions on my server it says "null"

Before Reload:  https://gyazo.com/6244ac6f50427195640578b5403504ca
After Reload: https://gyazo.com/6d784978ed70ca5f30f5355621aeb577

My config:
 -snip- https://gist.github.com/LittleGamerPlayz/7de0a73b82f6b544c94dbbf5e0567eee

**Comment by novucs** [comment]
Please upload your formatted config to https://gist.github.com/ along with your logs. An error may have occurred in console, that'd help me track down this issue much faster.

**Comment by LittleGamerPlayz** [comment]
https://gist.github.com/LittleGamerPlayz/7de0a73b82f6b544c94dbbf5e0567eee

**Comment by novucs** [comment]
And the logs from when the error happened?

**Comment by novucs** [comment]
No response, unable to reproduce the bug and if it were a hard server reload then that's not supported.
