### ISSUE TITLE
MVdW rank:# placeholder not working properly

### ISSUE THREAD

**Issue by xDacon** [novucs/factions-top#33]
The {factionstop_rank:#} placeholder isn't exactly working for me
{factionstop_rank:last} placeholder works fine, but if I try something like {factionstop_rank:2} it will just show as `-`

Example of using {factionstop_rank:2) in latest version of featherboard: https://prnt.sc/fd6nqa
`    test:
      text:
      - '&fTest {factionstop_rank:2}'
      interval: 60
      random: true`

i'm using the latest version of the plugin, and testing with the default config. I've tested the placeholder while using mysql as storage method and also tested with using default .db file for storage

Server version: PaperSpigot 1.11.2
Full server log: https://hastebin.com/erixiropiv.md

any help is greatly appreciated

**Comment by novucs** [comment]
Could you try the latest development build to see if that helps at all?
https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE

**Comment by xDacon** [comment]
Same issue with latest development build

> Edit: I know this sounds like a dumb question, but are there are more than 2 factions on your "/ftop"?
Yes

**Comment by novucs** [comment]
Download the patched build here: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE
