### ISSUE TITLE
Faction balance resetting on restart?

### ISSUE THREAD

**Issue by Shadnlil** [novucs/factions-top#35]
Hello, currently i have been using your plugin for my server, everything has gone great so far! But i've come across this glitch whenever i restart my server, All faction balances don't count towards the faction worth without withdrawing it then depositing again, but now its completely wiped the faction balances, it was all fine before i downloaded the plugin.

I hope you can help!

Thanks
Shadnlil - Owner of bunnyrealms.com

**Comment by novucs** [comment]
How do you mean it's now "completely wiped" the faction balances? FactionsTop does not make any economy changes, it reads but does not write. As for FactionsTop not finding the faction balances, which version of factions are you running?

**Comment by Shadnlil** [comment]
All factions in my server, their balance has completely gone, And the version is : 2.10.0

**Comment by Shadnlil** [comment]
One faction lost around 1.5 million in their factions balance

**Comment by novucs** [comment]
Yep, that would not have been FactionsTop's fault since it makes absolutely no economy changes. You still have not answered these two questions though:
- Do you have Essentials installed?
- Do you have Vault installed?
I need them answered in order for me to be able to even attempt to reproduce the issue you was having with faction balances not being counted on the ftop totals.

**Comment by Shadnlil** [comment]
Sorry, i did not see those. Yes i have both installed

**Comment by novucs** [comment]
Alright thanks, I'll take a little look when I get some free time.

**Comment by Shadnlil** [comment]
Thanks, I really need it fixed ASAP since i need to restart my server

**Comment by novucs** [comment]
If you need it fixed ASAP, then submit a PR request with the fix in it. I do not have much free time, yet this project is free and open source.

**Comment by Shadnlil** [comment]
How long do you think it'd take you?

**Comment by novucs** [comment]
Depends if I'd be able to reproduce your issue or not. I am not going to bother until I have free time and actually feel like working on this project, which won't be for quite a while.

**Comment by Shadnlil** [comment]
Hmm, What is a "PR request" ?

**Comment by Shadnlil** [comment]
Also, i've tried reloading the plugin and resyncing the worth but it all still works, only happens with restart

**Comment by Square04299** [comment]
I have the same probleme
Before : https://puu.sh/wk0WK/b0ff4479e0.png
After i stopped / reload the server : https://puu.sh/wk10K/5d5199440e.png
i had to give me back the money so he can calculate

**Comment by novucs** [comment]
If you wish to get the development build, it's right here: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE
