### ISSUE TITLE
Weird spam in console.

### ISSUE THREAD

**Issue by SnakeDaoust1232** [novucs/factions-top#37]
https://gyazo.com/b9705ff321b495c3c11605d3a10aa135

Newest verison of tacospigot and the newest verison of FactionsTop.

**Comment by MakeItReaal** [comment]
uhm maybe no support

**Comment by novucs** [comment]
Spigot sided issue, this message gets sent to console when you downgrade a newer world. Use this to simply filter the harmless warning:
https://www.spigotmc.org/resources/consolefilter.38208/
