### ISSUE TITLE
Spawner's Not Being Recognized

### ISSUE THREAD

**Issue by HV3** [novucs/factions-top#39]
I know for a fact im probably doing something wrong but would just like a push in the right direction on how to set it up so it will read them and show them on the f top command.

Thanks!

here is the config file - https://pastebin.com/eMfZe1Lu

**Comment by DuckCraftPvP** [comment]
you know im not novucs right?

**Comment by DuckCraftPvP** [comment]
- '&e&l-- Spawners --'
    - '&dSlime: &b{count:spawner:slime}'
    - '&dSkeleton: &b{count:spawner:skeleton}'
    - '&dZombie: &b{count:spawner:zombie}'
    - '$dSpider: &b{count:spawner:spider}'
    - '$dBlaze: &b{count:spawner:blaze}'
    - '$dCreeper: &b{count:spawner:creeper}'
    - '$dIron Golem: &b{count:spawner:iron_golem}'
    - '$dSpider: &b{count:spawner:cow}'

add a new line for each mob, like for cavespider do
- '$dCave Spider:&b{count:spawner:cave_spider}'

**Comment by HV3** [comment]
Oh I thought this was the f top thread my bad.. but that's what I'm doing and there still not being recognized like the spider, zombie, pig, cow etc..

**Comment by novucs** [comment]
What version/fork of spigot and factions are you running? Does this build fix your problem?
https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE

**Comment by HV3** [comment]
now it's just the iron golems im having issue's with im putting them as villager_golem, ill check that build out tho.. and let u know

**Comment by DuckCraftPvP** [comment]
iron_golem not villager_golem

**Comment by novucs** [comment]
Thanks @DuckCraftPvP
