### ISSUE TITLE
iron golem

### ISSUE THREAD

**Issue by hazallen321** [novucs/factions-top#4]
i cant get it to calculate the price of a iron golem 
- '&dIronGolem: &b{count:spawner:irongolem}'

it doesnt count it in faction land how do i fix it

**Comment by novucs** [comment]
Read the documentation within the config file, you need to use iron_golem.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

{count:spawner:iron_golem}

**Comment by hazallen321** [comment]
ok thanks
