### ISSUE TITLE
Plugin not working on latest spigot/paper

### ISSUE THREAD

**Issue by imaBASKET** [novucs/factions-top#40]
Seems to be broken on latest version.
https://hastebin.com/opixetayik.vbs

**Comment by novucs** [comment]
What version and fork of factions are you running?

**Comment by imaBASKET** [comment]
I was using 1.12, with factions 2.13-snapshot, however I see you recently (within past day) added support for it (though no download seems to be available)

I tried compiling it myself but I seem to have issue building the hooks.

**Comment by novucs** [comment]
Here is the download if you'd like to test it out: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE

**Comment by imaBASKET** [comment]
seems to work just fine, thanks!
