### ISSUE TITLE
Factions Money Problem

### ISSUE THREAD

**Issue by MrRobotMann** [novucs/factions-top#42]
When I restart my server some factions loses their balance. 

please help.

**Comment by novucs** [comment]
Please upload a copy of your log where this does happen to https://gist.github.com/
What factions build are you running?
What version of spigot are you running?
What version of vault?
Are you using Essentials?

**Comment by MrRobotMann** [comment]
It does not appear in logs it is just happening. I'm using the latest version of FactionsUUID ( PAID Version )
I'm running paper spigot 1.8.8, I'm using the latest version of vault and yes I'm using essentials.And yes all top 10 factions loses their faction balance.

**Comment by novucs** [comment]
>  When you say some, you mean others load up perfectly fine?
> What's the rough percentage of faction balances that do not load in?
> Is this just faction bank balances or player balances included?

I would still like the log file.

**Comment by MrRobotMann** [comment]
Log: https://hastebin.com/comowopize.md

**Comment by novucs** [comment]
And the other questions that you haven't yet answered?

**Comment by MrRobotMann** [comment]
I answered them please take a look at my previous messages.

"It does not appear in logs it is just happening. I'm using the latest version of FactionsUUID ( PAID Version )
I'm running paper spigot 1.8.8, I'm using the latest version of vault and yes I'm using essentials.And yes all top 10 factions loses their faction balance."

**Comment by novucs** [comment]
Is that bank balance or player balance?

**Comment by MrRobotMann** [comment]
bank balance

**Comment by MrRobotMann** [comment]
So ? Have you found the problem ?

**Comment by novucs** [comment]
No, I haven't been able to reproduce your issue.

**Comment by novucs** [comment]
I still haven't been able to reproduce your issue sadly, this issue was probably down to you using an old version of FactionsTop. Either way, the use of FactionsUUID is deprecated now since it's so outdated. If you're still running a server and you haven't already, I recommend upgrading to LegacyFactions which as proven to work very well with FactionsTop.
