### ISSUE TITLE
Iron Golem and Pigmen spawners not showing in ftop

### ISSUE THREAD

**Issue by TheRazerEyes** [novucs/factions-top#43]
Not sure why but the /ftop does not show iron golem spawners nor does it show pigmen spawners, I've tried to fix this by changing it to iron-golem and spawner:99 but nothing works?

https://pastebin.com/FmPwFbim

Please help

**Comment by novucs** [comment]
As displayed in the configuration documentation: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
