### ISSUE TITLE
Factions 2.11 Compatibility

### ISSUE THREAD

**Issue by zFrost87** [novucs/factions-top#44]
Doesn't seem to be compatible with Factions 2.11
[https://hastebin.com/luxemiwuqa.vbs](https://hastebin.com/luxemiwuqa.vbs)

**Comment by H0CKEY** [comment]
I have had the same problem, hoping the author of the plugin will respond

**Comment by novucs** [comment]
I simply do not understand why people are running outdated builds... Factions 2.12.x has been released ages ago now. For whatever reason you are choosing to run an outdated build, here is some support: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE
