### ISSUE TITLE
Reloading

### ISSUE THREAD

**Issue by HellaMixel** [novucs/factions-top#46]
I was editing the config changing the text, and after I use plugman to reload the plugins so I don't have to /reload or /restart. The issue I am having is I will join a faction, and give myself money, and do /f top and it shows that faction with the currency. After I reload the plugin when I fix the text, and I do /f top, the faction is gone. So I was like okay maybe I just have to add money back and it will fix back to what currency it was before. It didn't, it reset the entire currency back to 0. It'll be a problem when donors and etc donate and they get their currency and their faction is on the top list, then I have to do a reload and all their currency and f top resets. 

Plugins: 
http://imgur.com/a/q8rQF

**Comment by HellaMixel** [comment]
I guess you can say it's not updating the currency, or faction, after a reload?

**Comment by novucs** [comment]
Full plugin reloads are not supported. In order to fetch updated values from the configuration, simply use `/ftopreload`. Then to resynchronize the updated values, use `/ftoprecalc`
