### ISSUE TITLE
I think my server crashed because of your plugin

### ISSUE THREAD

**Issue by MrRobotMann** [novucs/factions-top#47]
Hi,

My server crashed and when I saw the crash report I think that your plugin caused the crash

Crash Report: https://hastebin.com/meliqahawe.md

**Comment by novucs** [comment]
Please learn to read crash reports before giving them to me. Your fault is here:

net.hydrotekz.BlowableObsidians.listeners.Listener.onEntityExplode(Listener.java:83)
