### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by MrRobotMann** [novucs/factions-top#48]
Hi, I'm having this error in my console 

Error https://hastebin.com/enelunuqes.bash

**Comment by novucs** [comment]
Sadly I see absolutely nothing todo with FactionsTop in this stack trace and is the first time I've seen of this error. Is it possible you are missing a portion of the error?

**Comment by MrRobotMann** [comment]
Nope :/

**Comment by novucs** [comment]
Did you forcibly reload the server at any point before this error occured?

**Comment by MrRobotMann** [comment]
No, I didn't reload the server and the plugin. It weird this error happened only once it didn't happened again after I opened a ticket ^-^. I left my ticket open because I wanted you to know that this happened ;p

**Comment by novucs** [comment]
What build of paperspigot are you running?

**Comment by MrRobotMann** [comment]
git-PaperSpigot-"8b18730" | 1.8.8 R0.1-SNAPSHOT

**Comment by novucs** [comment]
The latest paper 1.8 is "a7b5303". This is all I can recomend right now as the error stems from either one of the dependencies being unloaded or your paper version is having troubles. Download this version here, do not unload ftop or its dependencies and you should be good to go: https://ci.destroystokyo.com/job/PaperSpigot/443/
