### ISSUE TITLE
/f top "Dupe Glitch in Scoreboard"

### ISSUE THREAD

**Issue by MrRobotMann** [novucs/factions-top#49]
Hi,

If you place a spawner and then you break it with silk touch it will be counted in /f top. Here is a video that shows exactly what I mean

Video https://www.youtube.com/watch?v=ee-WJ5aNK2w&feature=youtu.be

**Comment by novucs** [comment]
Someone is being naughty and cancelling the event, or atleast not firing it. This is the job for whoevers silk touch plugin you have. Make sure they either fire a new BlockBreakEvent or atleast do not cancel the current one they're making use of.

**Comment by MrRobotMann** [comment]
So it is my silk spawner plugin fault ?

**Comment by novucs** [comment]
Yes, tell the author of that plugin you're using to ensure the BlockBreakEvent is actually being fired if a block is being broken.
