### ISSUE TITLE
10.09 19:50:31 [Server] WARN Skipping BlockEntity with id 

### ISSUE THREAD

**Issue by SmokedBurger** [novucs/factions-top#5]
the error:
10.09 19:50:31 [Server] WARN Skipping BlockEntity with id 

has been spamming me constantly for the past few days. i think it's with the block detecting but i dont want to remove that feature.And to test if this plugin was the problem i have disabled the plugin and the error was gone. please fix this. thank you :D

**Comment by novucs** [comment]
This is not an issue with FactionsTop, it is an incompatibility issue with your world and the version of Spigot you are running. This message will appear when a chunk is loaded with an invalid BlockEntity id.
