### ISSUE TITLE
ERROR Could not pass event FactionClaimEvent to FactionsTop v1.1.2

### ISSUE THREAD

**Issue by H0CKEY** [novucs/factions-top#50]
My IGN Is H0CKEY, and I have been trying to get Factions Top to work for the past hour. It seems as the title message appears as an error, in the console.
Ex: 03.08 20:11:15 [Server] ERROR Could not pass event FactionClaimEvent to FactionsTop v1.1.2
I really would like to use this plugin, but if I can't get it to work I don't think I will be able to.
Problem: Factions won't show up in /f top
Edit: -snipped useless and badly formatted configuration-

**Comment by novucs** [comment]
I need the full stack trace and your factions version in order to resolve this issue. Please do not post logs or configuration files in plain text next time, it's incredibly hard to read. I recomend you put them on https://gist.github.com/.

**Comment by novucs** [comment]
Duplicate issue https://github.com/novucs/factions-top/issues/44
