### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by SuperJogosDBZ** [novucs/factions-top#57]
How can I hook the plugin with another plugin?

Example of what I want to do:
http://prntscr.com/ghd7gz

**Comment by novucs** [comment]
Currently FactionsTop supports MVdW placeholders API, so any plugin that uses this should work. Does that server use this FactionsTop plugin?

**Comment by SuperJogosDBZ** [comment]
the splayset is giving error when picking the factions.

**Comment by novucs** [comment]
Could you please give a reproducible example for this?

**Comment by novucs** [comment]
Oh you're actually programming something, right. What error is it that you're getting?

**Comment by SuperJogosDBZ** [comment]
https://pastebin.com/htDYfsND

**Comment by novucs** [comment]
May I see the entire TopManager.java file?

**Comment by SuperJogosDBZ** [comment]
https://ghostbin.com/paste/nottb

**Comment by novucs** [comment]
No, the entire file. I need accurate line numbers to debug.

**Comment by SuperJogosDBZ** [comment]
https://ghostbin.com/paste/ed9sd

**Comment by novucs** [comment]
You've given me two entirely different snippets, one telling me that `}` was the cause of the null pointer exception. I'm going to suggest that you just use the API that I've provided.

An example usage: https://github.com/novucs/factions-top/blob/master/example/src/main/java/com/example/plugin/ExamplePlugin.java

(Copy this entire class and make no modifications) https://github.com/novucs/factions-top/blob/master/example/src/main/java/com/example/plugin/FactionsTopApi.java

**Comment by SuperJogosDBZ** [comment]
My encoder has tried everything but it does not work.

**Comment by novucs** [comment]
If you want me to help you, then at least supply me with new and relavent information.

**Comment by SuperJogosDBZ** [comment]
Can it provide your bitbucket server? I want to give you permission to see the plugin.

**Comment by novucs** [comment]
My bitbucket username is novucs.

**Comment by SuperJogosDBZ** [comment]
Ready, my nick there is vhtk the name of the project is worldtop.

**Comment by SuperJogosDBZ** [comment]
Could see the WorldTop project bitbucket?

**Comment by novucs** [comment]
Your code still [casts it to a list](https://bitbucket.org/worldpvpnetwork/world-top/src/4c49b65eb773ece78fe21b39f91571aefabfcdd9/src/com/worldpvp/supertop/managers/TopManager.java?at=master&fileviewer=file-view-default#TopManager.java-135). Just use the API I linked you.

**Comment by SuperJogosDBZ** [comment]
Check the code again, the code was out of date, it's now up to date.

**Comment by SuperJogosDBZ** [comment]
I updated now!

**Comment by novucs** [comment]
It's still not using the API I've supplied. Take a look at this example plugin: https://github.com/novucs/factions-top/tree/master/example/src/main/java/com/example/plugin

**Comment by SuperJogosDBZ** [comment]
How do I get the faction list for this class?

**Comment by SuperJogosDBZ** [comment]
There is no class in this api to pick up the faction list, how do I?
