### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by DarkNova101** [novucs/factions-top#58]
So, I am lost on how to fix this , I am running MassiveCraft Factions on my server along with this plugin plus a bunch more. [Here ](https://pastebin.com/jFDPVPsN)is the error message.

**Comment by novucs** [comment]
Are you using EpicSpawners? If so, please update to the latest version.

**Comment by DarkNova101** [comment]
i am using epic spawners and ill check the version shortly.

**Comment by novucs** [comment]
Let me know if this fixes your issue. To reproduce that error, place an EpicSpawners spawner in a chest and close it.

**Comment by novucs** [comment]
Thanks for notifying me, it looks like Songoda flip-flopped back on the API again... Why they think doing this is a good idea is beyond me. If it happens again without warning, I'll consider dropping support for EpicSpawners. For the time being, here is a build that should work for you: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE

**Comment by DarkNova101** [comment]
Alright, thanks.
