### ISSUE TITLE
Worth Value Placeholder w/ Other Plugins

### ISSUE THREAD

**Issue by Tyguy2464** [novucs/factions-top#59]
I am using FactionsUUID to customize what displays when you do /f show. I am trying to get it to display the value of the faction that is being shown, but I can't find any placeholder that will allow this. I've tried {worth:total} but in /f show it just displays {worth:total} instead of a number.

**Comment by novucs** [comment]
FactionsUUID will need to implement this placeholder itself. I suggest you do not use that plugin either and switch to LegacyFactions as there are many flaws with it that breaks compatibility.
