### ISSUE TITLE
Adding a mySQL

### ISSUE THREAD

**Issue by Alexloudmouth** [novucs/factions-top#6]
Hi i have been using your /f top plugin now for a good bit. but i don't see anywhere too setup the MySQL info and i was hoping you might add this. thank you!

**Comment by novucs** [comment]
Modify the JDBC URL to suit your needs.

https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html

Example:
jdbc:mysql://{address}:{port}/{database}
jdbc:mysql://127.0.0.1:3306/minecraft
