### ISSUE TITLE
MVdW Placeholder not working.

### ISSUE THREAD

**Issue by Scuffi** [novucs/factions-top#61]
Hi, I'm using deluxechat so I have to type mvdw_ before every placeholder from MVdW placeholderapi. The factionstop_rank:* placeholder isn't working and just shows %mvdw_factionstop_rank:*% in chat. I'm not sure if this is a deluxechat error, or I'm missing something? Anyways. Thanks.

**Comment by Scuffi** [comment]
Also when I do /featherboard parse it just shows {factionstop_rank:*} meaning it's not working correctly with MVdW. Is there something I need to enable?

**Comment by novucs** [comment]
[This latest build should have what you're looking for.](https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE)
```MVdW Placeholders:
- {factionstop_name:*}
- - The faction name of a rank by replacing * with a number.
- - The faction name in last place by replacing * with "last".
- {factionstop_rank:player}
- - The rank of the players faction if valid, otherwise faction-not-found text.```

The placeholder you would want to use is `{factionstop_rank:player}`.
