### ISSUE TITLE
Adding support for MergedSpawners

### ISSUE THREAD

**Issue by UnrealisticBeing** [novucs/factions-top#63]
Woops, accidentally hit enter and it submitted. I was hoping you could add support for MergedSpawners by vk2gpz for obvious reasons. If spawners are merged then f top only counts them as one. The dev says he has a public API so it shouldn't be too hard.

**Comment by UnrealisticBeing** [comment]
Can I get a message back when this is read? It's kind of urgent because my players like to see their worth on /f top

**Comment by novucs** [comment]
Duplicate of https://github.com/novucs/factions-top/issues/60
Also, if it's urgent, make a PR of this yourself. I'm currently far too busy to be working free, open source Minecraft projects.
