### ISSUE TITLE
GUI next page icons not working

### ISSUE THREAD

**Issue by Tree182** [novucs/factions-top#65]
The next icon in the GUI has turned green but is not working when clicked (does not go to the next page)

my config is: 

https://pastebin.com/A9H145UQ

**Comment by novucs** [comment]
Could you get me a 100% reproducible test case for this? I've not been able to reproduce. Include factions, vault, essentials, and spigot versions. How many factions to create and any other neice details required. Thanks.

**Comment by Tree182** [comment]
Im sorry, its because I'm an idiot. Ive fixed it now.

I had the commands.yml set to do f top and ftop as alias, thats what was doing it.

**Comment by novucs** [comment]
Ah so you made a third party plugin always execute the same page. Thanks for letting me know. I'm sure others will come to me with the same issue :p
