### ISSUE TITLE
Where to set Chest prices// new spawners does not work.

### ISSUE THREAD

**Issue by MisterZet** [novucs/factions-top#68]
how can I set chest prices?
2nd
When I make add entities to spawners it does not show my config:
-  spawner-prices:
    skeleton: 30000.0
    zombie: 25000.0
    slime: 75000.0
    cow: 100.0

-    lore:
    - '&e&l-- General --'
    - '&dTotal Worth: &b{worth:total}'
    - '&dBlock Worth: &b{worth:block}'
    - '&dChest Worth: &b{worth:chest}'
    - '&dSpawner Worth: &b{worth:spawner}'
    - '&dPlayer Balances: &b{worth:player_balance}'
    - '&dFaction Bank: &b{worth:faction_balance}'
    - ''
    - '&e&l-- Spawners --'
    - '&dSlime: &b{count:spawner:slime}'
    - '&dSkeleton: &b{count:spawner:skeleton}'
    - '&dZombie: &b{count:spawner:zombie}'
    - '&dCow: &b{count:spawner:cow}'
    - ''
    - '&e&l-- Materials --'
    - '&dEmerald Block: &b{count:material:emerald_block}'
    - '&dDiamond Block: &b{count:material:diamond_block}'
    - '&dGold Block: &b{count:material:gold_block}'
    - '&dIron Block: &b{count:material:iron_block}'
    - '&dCoal Block: &b{count:material:coal_block}'

**Comment by novucs** [comment]
Currently it is not possible to calculate prices the of chests themselves, only their contents are calculated. As for your issue with displaying additional entities, make sure you update the command + gui configurations accordingly. I assume you've only configured one.
