### ISSUE TITLE
Support for factions UUID & Colour code suport

### ISSUE THREAD

**Issue by AlexTeal03** [novucs/factions-top#69]
If possible could it be able to change colour codes?

Such as in /ftop
(&e)#1 Test
(&7)#2 Test2
(&6)#3 Test3
And reset &c

Also this can apply with chat [&e#1] [&7#2] [&6#3] & rest [&c(rank)]

Also the plugin is not working well on my server with FactionsUUID (Could this be implemented?)

**Comment by novucs** [comment]
Similar feature request already made here: https://github.com/novucs/factions-top/issues/26
FactionsUUID has recently undergone several updates that should resolve your issues. I am uncertain when this will be released to spigot but you may build from source here: https://github.com/drtshock/Factions
