### ISSUE TITLE
Plugin not booting

### ISSUE THREAD

**Issue by Mr4Skinz** [novucs/factions-top#72]
Plugin won't boot.

Do you guys have a discord server btw?
Error: https://imgur.com/a/TKj51
Ver: https://imgur.com/a/oUhh9

**Comment by novucs** [comment]
It says in the error, H2 was forcefully downloaded and a reboot may be required. Reboot and it should load fine. I do not have a discord server as I simply don't have enough time to give 24/7 free support for this free resource.
