### ISSUE TITLE
Count Spawners

### ISSUE THREAD

**Issue by SuperJogosDBZ** [novucs/factions-top#73]
I have a spawner stack plugin, would you like instructions on what parts of the FactionsTop code my developer should tinker with so the spawner count works correctly?

**Comment by novucs** [comment]
If this is a public spawner stack plugin, please send me the link to it and I'll add support when I have spare time. Unless you're willing to create a PR for this, which I'll gladly accept. If this spawner stack plugin is private, then I'm afraid there's not much point in me keeping public support for it.

**Comment by SuperJogosDBZ** [comment]
It is a private plugin, but if you are interested in getting support, I can make a donation to your paypal to help.

**Comment by novucs** [comment]
I'm sorry but I really do not have much time spare, especially for maintaining private forks of this project. Feel free to contact another developer to hook into this or modify plugin, it's all MIT licensed so you can do whatever you feel with this project. Thanks for understanding. :)

**Comment by novucs** [comment]
FactionsTopPlugin, and create a maven module like what I created for EpicSpawners.
