### ISSUE TITLE
/f top

### ISSUE THREAD

**Issue by SayNada** [novucs/factions-top#74]
/f top works
but when doing /f top (number) it goes to another f top page which is broken.

Please make it so /f top (number) is same as doing /ftop (number)

**Comment by novucs** [comment]
Do you have another ftop plugin installed, or another ftop built into your factions version?

**Comment by SayNada** [comment]
@novucs another f top built in (the factionsuuid/1.6.9.5 default one). The command /f top works, /ftop also works but /f top (page number) goes to the old one

**Comment by novucs** [comment]
Is there no method of disabling the ftop within that plugin?

**Comment by novucs** [comment]
Download the latest build here, this should resolve your issue: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE
