### ISSUE TITLE
All dependencies

### ISSUE THREAD

**Issue by SuperJogosDBZ** [novucs/factions-top#76]
Can you provide all dependencies of the plugin for my developer to be able to make updates?

**Comment by novucs** [comment]
They're all already there, use maven. To build the project, just use the command `mvn clean install`.

**Comment by SuperJogosDBZ** [comment]
http://prntscr.com/imf5uf erro download

**Comment by novucs** [comment]
Feel free to resolve this and make a PR. I assume the maven repo that once supported this is now offline.

**Comment by SuperJogosDBZ** [comment]
Can you send me what you have?
