### ISSUE TITLE
Reload sync/ display 

### ISSUE THREAD

**Issue by dylanbabiy** [novucs/factions-top#8]
After restarting the server or resynchronising the plugin the faction needs to be online and modify there factions amount in order for it to appear back on the leaderboard.

For example my factions has 200k I reload the server, my faction isn't there, I then sell something to modify my balance and it then updates the leaderboard.

It's annoying when you want to see how much money you are away from f top but the other fac is offline so it doesn't display.

**Comment by novucs** [comment]
Talked to you over on Spigot, I am unable to reproduce this with everything you've said. If anybody could provide me with the exact conditions to reproduce this using the latest version of FactionsTop, I'd be able to fix it.

**Comment by mraxtr0** [comment]
I i'm french my Englich is not verry good ^^.
I have a problem.
Players have faction and i desactivate blocs and chests. And i reload server reload all and i see a faction with blocs ... ? You kan't help my please  ? add me skype so i can better tell you :D Skype -> MrAxtr0           ( Nice plugin man ;) )

**Comment by novucs** [comment]
I've just noticed you mentioning hard reloading the server, I do not support this. If you wish to fully reload everything on the server, I suggest you simply perform a reboot.
