### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by gb-factory** [novucs/factions-top#80]
When i start the server i get this error in console
https://hastebin.com/exavevuluh.vbs

I also downloaded all libs, with the version provided by novcus and with the latest version from the official website but there is the same error!

Please fix or help me to solve this!

**Comment by novucs** [comment]
Download all these and stick them in `./lib`, where `.` is the server root directory (the one that contains `spigot.yml`).
`http://repo2.maven.org/maven2/org/slf4j/slf4j-api/1.7.9/slf4j-api-1.7.9.jar`
`http://repo2.maven.org/maven2/org/slf4j/slf4j-nop/1.7.9/slf4j-nop-1.7.9.jar`
`http://repo2.maven.org/maven2/com/h2database/h2/1.4.192/h2-1.4.192.jar`
