### ISSUE TITLE
FactionTop can't connect to MySQL Database

### ISSUE THREAD

**Issue by ViperOfficial** [novucs/factions-top#81]
Hi,
This is my error code: https://pastebin.com/9ttnDpJL
It seems like it cant connect to the mySQL database but it does work in game though.

Could you please help me?

Thanks!

Viper

**Comment by novucs** [comment]
You'll need to validate the credentials are correct in the configuration, and double check the database is able to be connected by wherever you're connecting from. There's nothing else to it really, this error you sent is stemming from the MySQL JDBC itself, so if there were a bug (which is highly unlikely) you'd need to report it to Oracle.
