### ISSUE TITLE
Liquid currency is doubled

### ISSUE THREAD

**Issue by MegaNarwhal** [novucs/factions-top#9]
I have the FactionsTop configured to only take into account the money a faction and its members have in the economy plugin. Initially in /ftop, my faction's money is displayed as double what it actually is. If I type /ftoprec, the correct money is displayed in /ftop.
Config: http://pastebin.com/z2svjbfe

**Comment by novucs** [comment]
Could you find a way for players on your server to reproduce the duplicated money issue? Does it only affect specific worth types?

**Comment by MegaNarwhal** [comment]
I'm running the latest Spigot build at this time, and MassiveCraft's Factions 2.8.20. The money is displayed incorrectly when the server first starts, and shows as double the Faction's balance without including individual player balances. If /ftoprec is run, it seems to show the proper amounts.

**Comment by novucs** [comment]
I'll be assuming this was an old bug with running factionstop for the first time while not being fully synchronized with the server to start. /ftoprecalc as you have mentioned corrects this problem for the future.
