### ISSUE TITLE
Essentials Chat Support

### ISSUE THREAD

**Issue by Smadger1** [novucs/factions-top#93]
Hey,

I cannot seem to find any support for essentials chat? Is this correct or am I simply inept.

**Comment by Smadger1** [comment]
I'm inept! This is the prefix if anyone is wondering! {factions_top_rank}

**Comment by Phoenix616** [comment]
Currently it only supports PlaceholderAPI and MVdW Placeholders, so you might be able to add it with them if you either use a compatible chat plugin or find one that adds support for those placeholders in Essentials Chat.
