### ISSUE TITLE
Add PlaceholderAPI

### ISSUE THREAD

**Issue by FactionsOlzie** [novucs/factions-top#97]
I Believe that PlaceholderAPI should be supported because, this can be used by other plugins (Chat plugins) 
so people can put there faction top level in chat. I think that people would like this, it will look very neat:
Plugin Author of PlaceholderAPI is: @extendedclip

Link: https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by Phoenix616** [comment]
PlaceholderAPI is supported since a5e548a282465fd11f9af4d224a2887c60cdb60e. You can get development builds from [here](https://ci.minebench.de/view/Various/job/FactionsTop/).

**Comment by TheJoshue** [comment]
Where can placeholders be seen?
like {faction_top_1}

**Comment by rejvic** [comment]
> Where can placeholders be seen? like {faction_top_1}

was this ever found?

**Comment by Phoenix616** [comment]
It's [right there](https://github.com/novucs/factions-top/blob/a5e548a282465fd11f9af4d224a2887c60cdb60e/hook/clipplaceholderapi/src/main/java/net/novucs/ftop/hook/ClipPlaceholderAPIHook.java#L33-L45) in the linked commit.
