### ISSUE TITLE
Could not pass event ChunkLoadEvent to FactionsTop

### ISSUE THREAD

**Issue by Sahviiksil** [novucs/factions-top#98]
I've tried using multiple versions of factions, spigot etc. Every time I use FactionsTop my console gets flooded with this error. I've even tried using different worlds. 

The console errors just repeat themselves. 

https://gyazo.com/2f027f266e35d66561a26d3fa51e71fb <-- Link to error in console.

**Comment by Phoenix616** [comment]
You are using a different plugin and not this one.
